src/objects/Animal__c.object
<CustomObject>
    <fields>
        <fullName>Animal_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Animal Template</label>
        <referenceTo>Animal_Template__c</referenceTo>
        <relationshipLabel>Animals</relationshipLabel>
        <relationshipName>Animals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zoo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zoo</label>
        <referenceTo>Zoo__c</referenceTo>
        <relationshipLabel>Animals</relationshipLabel>
        <relationshipName>Animals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Animal_Origin__c.object
<CustomObject>
    <fields>
        <fullName>Animal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Animal</label>
        <referenceTo>Animal__c</referenceTo>
        <relationshipLabel>Animal Origins</relationshipLabel>
        <relationshipName>Animal_Origins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Animal Origin</label>
    <nameField>
        <label>Animal Origin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animal Origins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Animal_Template__c.object
<CustomObject>
    <label>Animal Template</label>
    <nameField>
        <label>Animal Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animal Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zoo__c.object
<CustomObject>
    <label>Zoo</label>
    <nameField>
        <label>Zoo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AnimalControllerTest.cls
@isTest
private class AnimalControllerTest {
    @testSetup
    static void setupTestData() {
        Zoo__c zoo = new Zoo__c();
        insert zoo;
        
        Animal_Template__c animalTemplate = new Animal_Template__c();
        insert animalTemplate;
        
        Animal__c animal = new Animal__c();
        animal.Weight__c = 100;
        animal.Zoo__c = zoo.Id;
        insert animal;
        
        Animal_Origin__c animalOrigin = new Animal_Origin__c();
        animalOrigin.Weight__c = 50;
        animalOrigin.Animal__c = animal.Id;
        insert animalOrigin;
    }
    
    @isTest
    static void shouldReturnAnimalWrapperWithAllData() {
        Zoo__c zoo = [SELECT Id FROM Zoo__c LIMIT 1];
        
        Test.startTest();
        List<AnimalController.AnimalsWrapper> animalsWrappers = AnimalController.getAnimals(zoo.Id);
        Test.stopTest();
        
        System.assert(!animalsWrappers.isEmpty(), 'animalsWrappers list should not be empty!');
        System.assert(animalsWrappers[0].animal != null, 'animal should NOT be null!');
        System.assertEquals(100, animalsWrappers[0].animal.Weight__c, 'animal.Weight__c should be 100!');
        System.assert(animalsWrappers[0].animalOrigin != null, 'animalOrigin should not be null!');
        System.assertEquals(50, animalsWrappers[0].animalOrigin.Weight__c, 'animalOrigin.Weight__c should be 50!');
    }
    
    @isTest
    static void animalWrapperAnimalOriginShouldBeNull() {
        Zoo__c zoo = [SELECT Id FROM Zoo__c LIMIT 1];
        delete [SELECT Id FROM Animal_Origin__c];
        
        Test.startTest();
        List<AnimalController.AnimalsWrapper> animalsWrappers = AnimalController.getAnimals(zoo.Id);
        Test.stopTest();
        
        System.assert(!animalsWrappers.isEmpty(), 'animalsWrappers list should not be empty!');
        System.assert(animalsWrappers[0].animalOrigin == null, 'animalOrigin should be null!');
    }
}