src/objects/Animal__c.object
<CustomObject>
    <fields>
        <fullName>Animal_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Animal Template</label>
        <referenceTo>Animal_Template__c</referenceTo>
        <relationshipLabel>Animals</relationshipLabel>
        <relationshipName>Animals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zoo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zoo</label>
        <referenceTo>Zoo__c</referenceTo>
        <relationshipLabel>Animals</relationshipLabel>
        <relationshipName>Animals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Animal_Origin__c.object
<CustomObject>
    <fields>
        <fullName>Animal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Animal</label>
        <referenceTo>Animal__c</referenceTo>
        <relationshipLabel>Animal Origins</relationshipLabel>
        <relationshipName>Animal_Origins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Animal Origin</label>
    <nameField>
        <label>Animal Origin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animal Origins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Animal_Template__c.object
<CustomObject>
    <fields>
        <fullName>Use_Origin_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Origin Data</label>
        <type>Checkbox</type>
    </fields>
    <label>Animal Template</label>
    <nameField>
        <label>Animal Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animal Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zoo__c.object
<CustomObject>
    <label>Zoo</label>
    <nameField>
        <label>Zoo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AnimalController.cls
public class AnimalController {
    
    public class AnimalsWrapper {
        @AuraEnabled
        public Animal__c animal;
        @AuraEnabled
        public Animal_Origin__c animalOrigin;
    }
    
    @AuraEnabled
    public static List<AnimalsWrapper> getAnimals(Id zooId) {
        List<Animal__c> animals = [SELECT Id, Name, Weight__c, Country__c, Animal_Template__r.Use_Origin_Data__c FROM Animal__c WHERE Zoo__c = :zooId];
        List<Animal_Origin__c> animalOrigins = [SELECT Id, Name, Weight__c, Country__c, Animal__c FROM Animal_Origin__c WHERE Animal__c IN :animals];
        
        List<AnimalsWrapper> animalsWrappers = new List<AnimalsWrapper>();
        
        for (Animal__c animal : animals) {
            AnimalsWrapper animalWrapper = new AnimalsWrapper();
            animalWrapper.animal = animal;
            
            for (Animal_Origin__c animalOrigin : animalOrigins) {
                if (animalOrigin.Animal__c != animal.Id) {
                    continue;
                }
                
                animalWrapper.animalOrigin = animalOrigin;
            }
            
            animalsWrappers.add(animalWrapper);
        }
        
        return animalsWrappers;
    }
}